name: Meson CI

on:
  push:
    branches: [ "tail" ]
  pull_request:
    branches: [ "tail" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Enable Homebrew
      uses: raviqqe/enable-homebrew@v1.0.0
    - name: Install Build Tools
      run: brew install x86_64-elf-gcc
      run: sudo apt install nasm
    - name: Install Meson
      run: pip3 install --user meson
    - name: Meson Setup
      run: meson setup build --cross-file x86_64.ini
    - name: Meson Build
      run: ninja -C build
